Repository mapshare/mobile-app-backend, pull requests merged in 2019-11, with the labels that each got.

#38 Fixed Bug With Adding Group
  routes/groups/groupsService.js
Labels: bug

#39 Server Side Changes For Add Leave And Delete Group
  models/group.js
  routes/groups/groups.js
  routes/groups/groupsService.js
Labels: enhancement

#40 Added required changes needed for group menu.
  index.js
  initialData.js
  models/group.js
  models/groupChatSubDocs/chatRoom.js
  mongoURL.js
  routes/groups/chatRoomService.js
  routes/groups/groups.js
  routes/groups/groupsService.js
  routes/index.js
Labels: enhancement

#41 add owner role into .env
  .env
Labels: enhancement

#42 Added Https Server
  https-server.js
  package-lock.json
  package.json
Labels: enhancement

#43 Fixed Https and app connection
  https-server.js
Labels: bug

#44 small fixes for mark request in front end
  routes/groups/groups.js
  routes/groups/groupsService.js
Labels: enhancement

#45 Group feed and bug fix
  initialData.js
  models/groupFeedSubDocs/post.js
  package-lock.json
  package.json
  routes/groups/chatRoomService.js
  routes/groups/groupFeedService.js
  routes/groups/groups.js
  routes/groups/groupsService.js
Labels: enhancement

#47 parse upload image for add mark
  routes/groups/groupsService.js
Labels: enhancement

#49 Optimizations and Additions for Frontend
  models/group.js
  routes/groups/groupFeedService.js
  routes/groups/groups.js
  routes/groups/groupsService.js
Labels: bug, enhancement
